// ═══════════════════════════════════════════════════════════
// BUKD TEMPLATE SYSTEM — Theme Definitions
// ═══════════════════════════════════════════════════════════

import type { ThemeKey, ThemeDefinition } from './types';

export const THEMES: Record<ThemeKey, ThemeDefinition> = {
  luxurySoft: {
    key: 'luxurySoft',
    name: 'Luxury Soft',
    bgPrimary: '#FDFBF7',
    bgSecondary: '#F7F3ED',
    textPrimary: '#1A1A1A',
    textSecondary: '#6B6B6B',
    textMuted: '#A3A3A3',
    accent: '#B8977E',
    accentHover: '#A07D62',
    border: '#E8E2D8',
    cardBg: '#FFFFFF',
    headingFont: "'Playfair Display', serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '400',
    sectionGap: '140px',
    density: 'airy',
    isDark: false,
    borderRadius: '0px',
  },
  modernBold: {
    key: 'modernBold',
    name: 'Modern Bold',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#F8F9FA',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    accent: '#6B21A8',
    accentHover: '#581C87',
    border: '#E2E8F0',
    cardBg: '#FFFFFF',
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '700',
    sectionGap: '100px',
    density: 'balanced',
    isDark: false,
    borderRadius: '16px',
  },
  warmNeutral: {
    key: 'warmNeutral',
    name: 'Warm Neutral',
    bgPrimary: '#FAF8F5',
    bgSecondary: '#F0ECE5',
    textPrimary: '#2D2A26',
    textSecondary: '#6B655D',
    textMuted: '#A39E95',
    accent: '#C17F59',
    accentHover: '#A86B45',
    border: '#E5DFD7',
    cardBg: '#FFFFFF',
    headingFont: "'DM Sans', sans-serif",
    bodyFont: "'DM Sans', sans-serif",
    headingWeight: '700',
    sectionGap: '100px',
    density: 'balanced',
    isDark: false,
    borderRadius: '20px',
  },
  darkLuxury: {
    key: 'darkLuxury',
    name: 'Dark Luxury',
    bgPrimary: '#0B0B0D',
    bgSecondary: '#141418',
    textPrimary: '#F5F5F7',
    textSecondary: '#A1A1AA',
    textMuted: '#71717A',
    accent: '#E8CFC0',
    accentHover: '#F5E6DD',
    border: '#27272A',
    cardBg: '#18181B',
    headingFont: "'Cormorant Garamond', serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '300',
    sectionGap: '120px',
    density: 'airy',
    isDark: true,
    borderRadius: '0px',
  },
  darkTech: {
    key: 'darkTech',
    name: 'Dark Tech',
    bgPrimary: '#09090B',
    bgSecondary: '#18181B',
    textPrimary: '#FAFAFA',
    textSecondary: '#A1A1AA',
    textMuted: '#71717A',
    accent: '#06B6D4',
    accentHover: '#22D3EE',
    border: '#27272A',
    cardBg: '#18181B',
    headingFont: "'JetBrains Mono', monospace",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '600',
    sectionGap: '80px',
    density: 'balanced',
    isDark: true,
    borderRadius: '12px',
  },
  darkEnergy: {
    key: 'darkEnergy',
    name: 'Dark Energy',
    bgPrimary: '#0A0A0A',
    bgSecondary: '#171717',
    textPrimary: '#FFFFFF',
    textSecondary: '#D4D4D4',
    textMuted: '#737373',
    accent: '#F472B6',
    accentHover: '#EC4899',
    border: '#262626',
    cardBg: '#171717',
    headingFont: "'Bebas Neue', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '400',
    sectionGap: '60px',
    density: 'dense',
    isDark: true,
    borderRadius: '8px',
  },
  darkAuthority: {
    key: 'darkAuthority',
    name: 'Dark Authority',
    bgPrimary: '#0F1419',
    bgSecondary: '#1A2332',
    textPrimary: '#F0EDE8',
    textSecondary: '#9CA3AF',
    textMuted: '#6B7280',
    accent: '#D4A853',
    accentHover: '#E5BD6A',
    border: '#2D3748',
    cardBg: '#1A2332',
    headingFont: "'Playfair Display', serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '600',
    sectionGap: '100px',
    density: 'balanced',
    isDark: true,
    borderRadius: '4px',
  },
  playfulBright: {
    key: 'playfulBright',
    name: 'Playful Bright',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#FFF7ED',
    textPrimary: '#1E1B4B',
    textSecondary: '#4338CA',
    textMuted: '#818CF8',
    accent: '#F97316',
    accentHover: '#EA580C',
    border: '#E0E7FF',
    cardBg: '#FFFFFF',
    headingFont: "'Quicksand', sans-serif",
    bodyFont: "'Quicksand', sans-serif",
    headingWeight: '700',
    sectionGap: '80px',
    density: 'balanced',
    isDark: false,
    borderRadius: '24px',
  },
  clinicalClean: {
    key: 'clinicalClean',
    name: 'Clinical Clean',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#F8FAFC',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    accent: '#0284C7',
    accentHover: '#0369A1',
    border: '#E2E8F0',
    cardBg: '#FFFFFF',
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '600',
    sectionGap: '80px',
    density: 'dense',
    isDark: false,
    borderRadius: '12px',
  },
  warmCare: {
    key: 'warmCare',
    name: 'Warm Care',
    bgPrimary: '#FEFDFB',
    bgSecondary: '#F5F0EB',
    textPrimary: '#3D3529',
    textSecondary: '#6B5F53',
    textMuted: '#A89E93',
    accent: '#7FB5A0',
    accentHover: '#5E9E86',
    border: '#E5DDD4',
    cardBg: '#FFFFFF',
    headingFont: "'Nunito', sans-serif",
    bodyFont: "'Nunito', sans-serif",
    headingWeight: '700',
    sectionGap: '120px',
    density: 'airy',
    isDark: false,
    borderRadius: '20px',
  },
  zenMinimal: {
    key: 'zenMinimal',
    name: 'Zen Minimal',
    bgPrimary: '#F9F7F4',
    bgSecondary: '#EDE9E3',
    textPrimary: '#3A3632',
    textSecondary: '#7A7570',
    textMuted: '#B5B0AA',
    accent: '#7D8B6A',
    accentHover: '#6A7859',
    border: '#DDD8D1',
    cardBg: '#FFFFFF',
    headingFont: "'Cormorant', serif",
    bodyFont: "'Work Sans', sans-serif",
    headingWeight: '300',
    sectionGap: '140px',
    density: 'airy',
    isDark: false,
    borderRadius: '4px',
  },
  industrialStrong: {
    key: 'industrialStrong',
    name: 'Industrial Strong',
    bgPrimary: '#1C1C1E',
    bgSecondary: '#2C2C2E',
    textPrimary: '#F5F5F5',
    textSecondary: '#AEAEB2',
    textMuted: '#636366',
    accent: '#FF453A',
    accentHover: '#FF6961',
    border: '#3A3A3C',
    cardBg: '#2C2C2E',
    headingFont: "'Barlow Condensed', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '700',
    sectionGap: '60px',
    density: 'dense',
    isDark: true,
    borderRadius: '8px',
  },
  energeticBrand: {
    key: 'energeticBrand',
    name: 'Energetic Brand',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#F0FDF4',
    textPrimary: '#0F172A',
    textSecondary: '#334155',
    textMuted: '#94A3B8',
    accent: '#10B981',
    accentHover: '#059669',
    border: '#E2E8F0',
    cardBg: '#FFFFFF',
    headingFont: "'Montserrat', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '800',
    sectionGap: '80px',
    density: 'balanced',
    isDark: false,
    borderRadius: '16px',
  },
  editorialMinimal: {
    key: 'editorialMinimal',
    name: 'Editorial Minimal',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#FAFAFA',
    textPrimary: '#1A1A1A',
    textSecondary: '#6B6B6B',
    textMuted: '#ABABAB',
    accent: '#1A1A1A',
    accentHover: '#404040',
    border: '#ECECEC',
    cardBg: '#FFFFFF',
    headingFont: "'Syne', sans-serif",
    bodyFont: "'DM Sans', sans-serif",
    headingWeight: '600',
    sectionGap: '140px',
    density: 'airy',
    isDark: false,
    borderRadius: '0px',
  },
  organicEarth: {
    key: 'organicEarth',
    name: 'Organic Earth',
    bgPrimary: '#F7F3EC',
    bgSecondary: '#EDE5D8',
    textPrimary: '#2D2B28',
    textSecondary: '#5C5650',
    textMuted: '#9E9589',
    accent: '#4A7C59',
    accentHover: '#3A6347',
    border: '#D9D0C4',
    cardBg: '#FDFBF7',
    headingFont: "'EB Garamond', serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '400',
    sectionGap: '140px',
    density: 'airy',
    isDark: false,
    borderRadius: '4px',
  },
  craftMinimal: {
    key: 'craftMinimal',
    name: 'Craft Minimal',
    bgPrimary: '#FAFAF8',
    bgSecondary: '#F0F0EC',
    textPrimary: '#2A2A28',
    textSecondary: '#7A7A76',
    textMuted: '#B0B0AC',
    accent: '#8B7355',
    accentHover: '#745F45',
    border: '#E0E0DC',
    cardBg: '#FFFFFF',
    headingFont: "'EB Garamond', serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '400',
    sectionGap: '160px',
    density: 'airy',
    isDark: false,
    borderRadius: '0px',
  },
  utilitarian: {
    key: 'utilitarian',
    name: 'Utilitarian',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#F3F4F6',
    textPrimary: '#111827',
    textSecondary: '#4B5563',
    textMuted: '#9CA3AF',
    accent: '#DC2626',
    accentHover: '#B91C1C',
    border: '#D1D5DB',
    cardBg: '#FFFFFF',
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headingWeight: '800',
    sectionGap: '48px',
    density: 'dense',
    isDark: false,
    borderRadius: '8px',
  },
};

/**
 * Get a theme definition by key, with fallback to modernBold.
 */
export const getTheme = (key: ThemeKey): ThemeDefinition => {
  return THEMES[key] || THEMES.modernBold;
};

/**
 * Generate CSS custom properties from a theme definition.
 * Apply these to a wrapper div via style={getThemeStyles(theme)}.
 */
export const getThemeStyles = (theme: ThemeDefinition): React.CSSProperties => ({
  '--t-bg-primary': theme.bgPrimary,
  '--t-bg-secondary': theme.bgSecondary,
  '--t-text-primary': theme.textPrimary,
  '--t-text-secondary': theme.textSecondary,
  '--t-text-muted': theme.textMuted,
  '--t-accent': theme.accent,
  '--t-accent-hover': theme.accentHover,
  '--t-border': theme.border,
  '--t-card-bg': theme.cardBg,
  '--t-heading-font': theme.headingFont,
  '--t-body-font': theme.bodyFont,
  '--t-heading-weight': theme.headingWeight,
  '--t-section-gap': theme.sectionGap,
  '--t-radius': theme.borderRadius,
  fontFamily: theme.bodyFont,
  backgroundColor: theme.bgPrimary,
  color: theme.textPrimary,
} as React.CSSProperties);

/**
 * Google Fonts import URL for all theme fonts.
 */
export const GOOGLE_FONTS_URL = 'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700&family=Bebas+Neue&family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=Cormorant:wght@300;400;500&family=DM+Sans:wght@400;500;600;700&family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&family=Montserrat:wght@400;500;600;700;800&family=Nunito:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Quicksand:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&family=Syne:wght@400;500;600;700;800&family=Work+Sans:wght@300;400;500;600&display=swap';
